// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/merge/shopping-card/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// CartCacheStore is an autogenerated mock type for the CartCacheStore type
type CartCacheStore struct {
	mock.Mock
}

// FindByUserID provides a mock function with given fields: ctx, ID
func (_m *CartCacheStore) FindByUserID(ctx context.Context, ID string) ([]*model.CartCache, error) {
	ret := _m.Called(ctx, ID)

	var r0 []*model.CartCache
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*model.CartCache, error)); ok {
		return rf(ctx, ID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*model.CartCache); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.CartCache)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveById provides a mock function with given fields: ctx, ID, userID
func (_m *CartCacheStore) RemoveById(ctx context.Context, ID string, userID string) error {
	ret := _m.Called(ctx, ID, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, ID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, u
func (_m *CartCacheStore) Save(ctx context.Context, u *model.CartCache) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CartCache) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCartCacheStore creates a new instance of CartCacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartCacheStore {
	mock := &CartCacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
