// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// AuthWorker is an autogenerated mock type for the AuthWorker type
type AuthWorker struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *AuthWorker) Login(ctx *gin.Context, email string, password string) (interface{}, error) {
	ret := _m.Called(ctx, email, password)

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, string, string) (interface{}, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, string, string) interface{}); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Signup provides a mock function with given fields: ctx, email, password
func (_m *AuthWorker) Signup(ctx *gin.Context, email string, password string) (interface{}, error) {
	ret := _m.Called(ctx, email, password)

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*gin.Context, string, string) (interface{}, error)); ok {
		return rf(ctx, email, password)
	}
	if rf, ok := ret.Get(0).(func(*gin.Context, string, string) interface{}); ok {
		r0 = rf(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*gin.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthWorker creates a new instance of AuthWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthWorker {
	mock := &AuthWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
